/* This file is autogenerated, do not edit*/
#include "vtdraw_automoc.dir/moc_canvas_widget_ZGBIW3EG5HIA7C.cpp"
#include "vtdraw_automoc.dir/moc_main_window_PDWQDELGOBWNIT.cpp"
#include "vtdraw_automoc.dir/moc_message_widget_XRKBLSHXA5KY3B.cpp"
#include "vtdraw_automoc.dir/moc_qt_interpreter_SJKRZURFDCGMJI.cpp"
#include "vtdraw_automoc.dir/moc_repl_widget_AWW4P6T2KNIT2C.cpp"
